### PR TITLE
Fix installing zend-diactoros on migration

### LINKED ISSUE #11: Migration fails due to unsatisfied deps
- [x] I was not able to find an [open](https://github.com/webimpress/zend-expressive-migration/issues?q=is%3Aopen) or [closed](https://github.com/webimpress/zend-expressive-migration/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

Provide a narrative description of what you are trying to accomplish:'
I'm updating Expressive 2.2 app to Expressive 3.0, following the [migration guide](https://docs.zendframework.com/zend-expressive/v3/reference/migration/#upgrading)

### Code to reproduce the issue

```console
$ composer require --dev zendframework/zend-expressive-migration
$  ./vendor/bin/expressive-migration migrate
```

### Expected results

Upgrade should complete (I think)

### Actual results
Upgrade proceeds apparently fine, but eventually emits the following failure:
```
composer require --dev zendframework/zend-component-installer zendframework/zend-expressive-too
ling --no-interaction
Using version ^2.1 for zendframework/zend-component-installer
Using version ^1.0 for zendframework/zend-expressive-tooling
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - zendframework/zend-httphandlerrunner 1.0.1 requires psr/http-message-implementation ^1.0
-> no matching package found.
    - zendframework/zend-expressive-tooling 1.0.0 requires zendframework/zend-expressive ^3.0 -> satisfiable by zendframework/zend-expressive[3.0.0].
    - zendframework/zend-expressive 3.0.0 requires zendframework/zend-httphandlerrunner ^1.0.1 -> satisfiable by zendframework/zend-httphandlerrunner[1.0.1].
    - Installation request for zendframework/zend-expressive-tooling ^1.0 -> satisfiable by zendframework/zend-expressive-tooling[1.0.0].
```
Then a couple of following steps fail like this:
```
Please provide the path to the application sources [src]:
Provided directory is: src
> expressive 'migrate:interop-middleware' '--src' 'src'
sh: 1: expressive: not found
Script expressive handling the expressive event returned with error code 127
Please provide the path to the application actions to be converted to request handlers [src]:
Provided directory is: src
> expressive 'migrate:middleware-to-request-handler' '--src' 'src'
sh: 1: expressive: not found
Script expressive handling the expressive event returned with error code 127
```

### PR DESCRIPTION
**Pull request by michalbundyra**
When it was explicitly required it was updated and then removed.
It should be always required on migration as Expressive v2 required it, and in Expressive v3 we can use any PSR-7 implementation. For compatibility it should be installed, and then it could be changed manually to another implementation.

Fixes #11 

- [x] Are you fixing a bug?
  - [x] Detail how the bug is invoked currently.
  - [x] Detail the original, incorrect behavior.
  - [x] Detail the new, expected behavior.
  - [x] Base your feature on the `master` branch, and submit against that branch.
  - [x] ~Add a regression test that demonstrates the bug, and proves the fix.~ - manual tests on https://github.com/weirdan/z-e-m-dep-bug repo
  - [ ] Add a `CHANGELOG.md` entry for the fix.

/cc @weirdan

### CODE REVIEW

File: src/MigrateCommand.php [hunk 1]
```diff
@@ -219,7 +219,6 @@ private function updatePackages(array $packages) : void
     {
         exec('rm -Rf vendor');
         exec('composer install --no-interaction');
-        exec('composer require "zendframework/zend-diactoros:^1.7.1"');
```
Comment (geerteltink) [inline src/MigrateCommand.php:222]: We had issues with this before. Without this line it didn't work.

/Cc @weierophinney  what did you try last week and would this work?

Comment (michalbundyra) [reply src/MigrateCommand.php:222]: @xtreamwayz Please note I add it below in `$require` variable.
This is in case we have explicitly defined zend-diactoros in composer, then it was updated here, and removed later on (in loop with commands, because it's one of expressive deps - defined on top of the file). We have to install it always on migration, for compatibility, but it should be done later - after removing packages.

Comment (geerteltink) [reply src/MigrateCommand.php:222]: I saw you added it. Just want to check with @weierophinney if he tried this solution and if it failed.

Comment (weierophinney) [reply src/MigrateCommand.php:222]: I did indeed try adding it to the `require` section (that was actually my first attempt), and it did not work. I found I had to do the explicit `composer require` above for it to work correctly.

**Comment by weierophinney** [comment]
> Expressive v2 required it, and in Expressive v3 we can use any PSR-7 implementation.

Yes and no. zend-expressive can use any PSR-7 implementation, but only as of v3. For the initial v3 skeleton to work, we need a PSR-7 implementation in place... and, moreover, working response and stream factory implementations. We would need to provide those for Expressive to work out-of-the-box, and the only ones we currently provide only work with Diactoros at this time; this is why the skeleton _requires_ zend-diactoros for v3.

We can only really address using alternate PSR-7 implementations once we have PSR-17 in place; until then, the skeleton is hard-coded to require zend-diactoros (though we can likely provide documentation for _removing it_ later, detailing how to create and register response and stream factories).

File: src/MigrateCommand.php (hunk 1 above)
Comment (weierophinney) [reply src/MigrateCommand.php:222]: Okay, so tried this locally; difference must be with the order in which the dev/non-dev requirements are installed, as it worked fine for me, both when used as a dev dependency of the project as well as used from a global installation.

**Review by weierophinney — APPROVED** [review]

**Comment by weierophinney** [comment]
Thanks, @webimpress!
